version: '3'
services:
  postgres:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: "${DB_USER}"
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
      POSTGRES_DB: "${DB_DATABASE}"
    ports:
     - "${DB_PORT}:5432"
    volumes:
      - nextportfolio_postgres:/var/lib/postgresql/data/

  web:
    build:
      context: ./
      dockerfile: ./.docker/web.Dockerfile
      args:
        APP_PORT: ${APP_PORT}
    restart: unless-stopped
    environment:
      DB_HOST: postgres
    ports:
      - "${APP_PORT}:3000"
    depends_on:
      - postgres

volumes:
  nextportfolio_postgres:
