import React from "react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import clsx from "clsx";
import { Header } from "@/app/layout.components/Header/Header";
import { Footer } from "@/app/layout.components/Footer/Footer";

const font = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
    <body className={clsx(
      font.className,
      "relative grid grid-rows-[auto_1fr_auto] min-h-screen bg-gray-100 text-gray-900",
    )}>
      <Header className="sticky top-0 inset-x-0"/>
      <main className="py-4">
        {children}
      </main>
      <Footer/>
    </body>
    </html>
  );
}
