name: ESLint

on:
  push:
    branches:
      - main

jobs:
  lint:
    name: Fix lint
    runs-on: ubuntu-latest
    steps:
      - name: Pulling codebase
        uses: actions/checkout@master
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Installing dependencies
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: install
      - name: Running lint fix
        uses: borales/actions-yarn@v3.0.0
        with:
          cmd: lint --fix
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          message: Auto-Fix Lint


